# Generated by Django 5.1.1 on 2024-10-03 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('art_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.art')),
                ('paint_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.paint')),
            ],
        ),
    ]
