# Generated by Django 5.1.1 on 2024-10-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_rename_images_product_images1_product_images2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.BooleanField(default=True),
        ),
    ]
