# Generated by Django 5.1.1 on 2024-11-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='art_type_offer',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
