# Generated by Django 5.1.1 on 2024-11-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_art_art_type_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_type_offer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
