# Generated by Django 5.1.1 on 2024-10-31 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_app', '0002_alter_coupons_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coupon_user', to='coupon_app.coupons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coupon_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
