# Generated by Django 5.1.1 on 2024-10-09 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_product_product_status'),
        ('variant_app', '0002_remove_variant_product_variant_variant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_app.product'),
        ),
    ]
