# Generated by Django 5.1.1 on 2024-10-15 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_cart'),
        ('variant_app', '0003_alter_variant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='variant_app.variant'),
            preserve_default=False,
        ),
    ]
