# Generated by Django 5.1.1 on 2024-10-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failure', 'Failure')], default='Pending', max_length=10),
        ),
    ]
