# Generated by Django 5.1.1 on 2024-10-28 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_order_payment_status'),
        ('coupon_app', '0002_alter_coupons_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupon_app.coupons'),
        ),
    ]
