# Generated by Django 5.1.1 on 2024-10-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_remove_wallet_transaction_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_transaction',
            name='credited_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
