# Generated by Django 5.1.1 on 2024-10-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_wallet_transaction_credited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet_transaction',
            old_name='credited_by',
            new_name='transaction_mode',
        ),
    ]
