# Generated by Django 5.1.1 on 2024-11-01 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_rename_credited_by_wallet_transaction_transaction_mode'),
        ('variant_app', '0003_alter_variant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='variant_app.variant'),
            preserve_default=False,
        ),
    ]
