# Generated by Django 5.1.1 on 2024-11-01 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_alter_review_variant'),
        ('variant_app', '0003_alter_variant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='variant_app.variant'),
            preserve_default=False,
        ),
    ]
