# Generated by Django 5.1.1 on 2024-11-04 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_alter_review_variant'),
        ('variant_app', '0003_alter_variant_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('request', 'Request'), ('approve', 'Approve')], default='pending', max_length=10)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged Product'), ('wrong_item', 'Wrong Item Sent'), ('not_satisfied', 'Not Satisfied with Product'), ('size_issue', 'Size or Fit Issue'), ('other', 'Other')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='variant_app.variant')),
            ],
        ),
    ]
