# Generated by Django 5.1.1 on 2024-11-04 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_return'),
        ('product_app', '0004_product_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='product_app.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.CharField(choices=[('damaged', 'Damaged Product'), ('wrong_item', 'Wrong Item Sent'), ('not_satisfied', 'Not Satisfied with Product'), ('other', 'Other')], max_length=20),
        ),
    ]
