# Generated by Django 5.1.1 on 2024-11-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_orderaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
