# Generated by Django 5.1.1 on 2024-11-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_remove_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
