# Generated by Django 5.1.1 on 2024-11-09 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_return_order_id'),
        ('product_app', '0004_product_product_status'),
        ('variant_app', '0003_alter_variant_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='return',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant_app.variant'),
        ),
        migrations.AlterUniqueTogether(
            name='return',
            unique_together={('product', 'variant', 'user', 'order_id')},
        ),
    ]
