# Generated by Django 5.1.1 on 2024-11-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0033_alter_return_product_alter_return_reason_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='return',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='return',
            name='order_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.order_details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='return',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='return',
            name='product',
        ),
    ]
