# Generated by Django 5.1.1 on 2024-11-09 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0034_alter_return_unique_together_return_order_details_and_more'),
        ('product_app', '0004_product_product_status'),
        ('variant_app', '0003_alter_variant_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='order_details',
        ),
        migrations.RemoveField(
            model_name='return',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='return',
            name='quantity',
        ),
        migrations.AddField(
            model_name='return',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='product_app.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.CharField(default='Other', max_length=200),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='return',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='variant_app.variant'),
        ),
    ]
