# Generated by Django 5.1.1 on 2024-11-10 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0035_remove_return_order_details_remove_return_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='product',
        ),
        migrations.RemoveField(
            model_name='return',
            name='user',
        ),
        migrations.RemoveField(
            model_name='return',
            name='variant',
        ),
        migrations.AddField(
            model_name='return',
            name='order_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='User.order_details'),
            preserve_default=False,
        ),
    ]
