# Generated by Django 5.1.1 on 2024-11-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0036_remove_return_product_remove_return_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return',
            old_name='order_details',
            new_name='order_item',
        ),
    ]
