# Generated by Django 5.1.1 on 2024-11-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0039_order_coupon_code_order_coupon_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupon_code',
            new_name='coupon_percentage',
        ),
    ]
