# Generated by Django 5.1.1 on 2024-11-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0040_rename_coupon_code_order_coupon_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
