# Generated by Django 5.1.1 on 2024-11-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0045_remove_userinformations_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='item_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('return', 'Return'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
